### PR TITLE
Cleanup numerous small issues in code base

### PR DESCRIPTION
**Pull request by adkulas**
A number of small things need to be cleaned up in the codebase. The following comment will contain a list of items to cleanup.
Let's tackle them together. Please add more to the list as you see them come up.

- [x] Change base.html and remove references from example
- [x] add static files from example for css and images
  - [static files found here](https://github.com/suhailvs/django-schools/tree/master/django_school/static)
  - need to add path to static files in settings.py see example settings.py found [here](https://github.com/suhailvs/django-schools/blob/master/django_school/django_school/settings.py)
- [x] model for patients_record has created_on field that is interger. Change this to datetime with default value of now()
- [x] django admin doesn't display all fields for users
  - modify the list display in the [admin.py](https://github.com/ece651-winter2019/ece651-group-project/blob/master/healthapp_project/healthapp_root/users/admin.py) file
- [x] Extend the admin interface to also show the inline profiles for patients and doctors
  - This [article](https://simpleisbetterthancomplex.com/tutorial/2016/11/23/how-to-add-user-profile-to-django-admin.html) may be helpful.
  - This task should involve adding the inline profiles that were commented out previously in [admin.py](https://github.com/ece651-winter2019/ece651-group-project/blob/master/healthapp_project/healthapp_root/users/admin.py)
- [x] Make it so that when admin logs in, you are taken to the admin dashboard
  - I believe this would just be a simple if statement to check if the logged in user is the admin
  - Potential good reference (https://stackoverflow.com/questions/32680706/how-to-have-specific-users-see-different-webpages-in-django). Still trying to figure out how to implement
  - This reference helped solve the issue ( https://stackoverflow.com/questions/29279893/how-to-redirect-my-own-login-to-admin-login-in-django)

### CODE REVIEW

**Comment by adkulas** [comment]
Take a look when you get a chance

**Comment by gaberch** [comment]
@jmcarrillog, any specific reason why bullet point number 4 was unchecked? I added the edits to close this out last night.

**Comment by jmcarrillog** [comment]
> @jmcarrillog, any specific reason why bullet point number 4 was unchecked? I added the edits to close this out last night.

@gaberch, Perhaps I edited the checkboxes by accident, without any reason. I am sorry.

**Comment by gaberch** [comment]
No problem. Just wanted to make sure that I didn't miss anything :)

**Pull request merged**
